format = """
[░▒▓](#a3aed2)\
[ $os ](fg:#090c0c bg:#a3aed2)\
[](fg:#a3aed2 bg:#769ff0)\
[ $directory ](fg:#e3e5e5 bg:#769ff0)\
[](fg:#769ff0 bg:#394260)\
[$git_branch](fg:#769ff0 bg:#394260)\
[](fg:#394260 bg:#212736)\
[$nodejs$rust$python](fg:#769ff0 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
[$status](bold red bg:#1d2230)\
[ ](fg:#1d2230)\
\n$character"""

[status]
disabled = false
format = ' $symbol$status '
map_symbol = true

[directory]
format = '$path'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
Documents = '󰈙'
Downloads = ''
Music = ''
Pictures = ''

[os]
disabled = false
format = '$symbol'

[os.symbols]
Windows = '󰍲'
Ubuntu = '󰕈'
Macos = '󰀵'
Linux = '󰌽'
Alpine = ''
Debian = '󰣚'

[git_branch]
symbol = ''
format = ' $symbol $branch '

[nodejs]
format = ' $symbol($version) '

[rust]
format = ' $symbol($version) '

[python]
symbol = ' '
format = ' $symbol($version) '

